# Generated by Django 4.2.14 on 2024-08-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_body_comment_booty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='booty',
            new_name='body',
        ),
    ]
